# Generated by Django 5.1.2 on 2024-10-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_details', models.CharField(max_length=255)),
                ('cust_reference', models.CharField(max_length=255)),
                ('trans_date', models.DateField()),
                ('val_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_number', models.CharField(max_length=50)),
                ('trans_ref', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
