# Generated by Django 5.1.2 on 2024-10-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionform',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
